export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"


export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"


export const GET_DATA_USER_SUCCESS = "GET_DATA_USER_SUCCESS"
export const GET_DATA_USER_FAILED = "GET_DATA_USER_FAILED"

export const LOGOUT = "LOGOUT"

export const UPDATE_PROFILE_USER = "UPDATE_PROFILE_USER"