
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"

export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS"

export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"

export const GET_POST_COUNT_SUCCESS = "GET_POST_COUNT_SUCCESS"

export const GE_MY_POSTS_COUNT_SUCCESS = "GE_MY_POSTS_COUNT_SUCCESS"

export const FILTER_POSTS_SUCCESS = "FILTER_POSTS_SUCCESS"
